apiVersion: v1
kind: ConfigMap
metadata:
  name: hub-files-etc-jupyterhub-templates
data:
  {{- (.Files.Glob "files/etc/jupyterhub/templates/*").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hub-usr-local-share-jupyterhub-static-external
binaryData:
  {{- $root := . }}
  {{- range $path, $bytes := .Files.Glob "files/static/external/*" }}
  {{ base $path }}: '{{ $root.Files.Get $path | b64enc }}'
  {{- end }}
